name: EmirUtils
version: '1.0.0'
main: xyz.emirdev.emirutils.EmirUtils
api-version: '1.21'
authors: [ EmirhanTr3 ]
loader: xyz.emirdev.emirutils.EmirUtilsPluginLoader
dependencies:
  server:
    LuckPerms:
      load: BEFORE
      required: true